/* Generated by tools/generate_ldpc_table.py; do not edit. */
#ifndef RTNC_GENERATED_LDPC_TEST_7_4_H
#define RTNC_GENERATED_LDPC_TEST_7_4_H

#include "../ldpc.h"
#include <stddef.h>
#include <stdint.h>

static const uint16_t ldpc_test_7_4_check_offsets[] = { 0U, 4U, 8U, 12U };
static const uint16_t ldpc_test_7_4_edge_variables[] = { 0U, 1U, 3U, 4U, 0U, 2U, 3U, 5U, 1U, 2U, 3U, 6U };

static const rtnc_ldpc_code_t ldpc_test_7_4 = {
    .variable_count = 7U,
    .information_count = 4U,
    .check_count = 3U,
    .edge_count = 12U,
    .check_offsets = ldpc_test_7_4_check_offsets,
    .edge_variables = ldpc_test_7_4_edge_variables,
    .parity_masks = NULL,
};

#endif
