#!/usr/bin/env python3
"""Generate deterministic C check-adjacency tables from a small JSON matrix."""

import argparse
import json
import pathlib
import sys


def render(source: pathlib.Path) -> str:
    spec = json.loads(source.read_text(encoding="utf-8"))
    if "parity_check_rows" in spec:
        rows = spec["parity_check_rows"]
    else:
        size = spec["circulant_size"]
        blocks = spec["circulant_blocks"]
        rows = [[] for _ in range(len(blocks) * size)]
        for block_row, block_columns in enumerate(blocks):
            for block_column, shifts in enumerate(block_columns):
                for local_row in range(size):
                    for shift in shifts:
                        rows[block_row * size + local_row].append(
                            block_column * size + (local_row + shift) % size
                        )
        rows = [sorted(row) for row in rows]
    variables = max(max(row) for row in rows) + 1
    offsets = [0]
    edges = []
    for row in rows:
        if len(row) < 2 or row != sorted(set(row)):
            raise ValueError("each check row must be sorted, unique, and degree >= 2")
        edges.extend(row)
        offsets.append(len(edges))
    name = spec["name"]
    guard = f"RTNC_GENERATED_{name.upper()}_H"
    values = lambda xs: ", ".join(f"{value}U" for value in xs)
    information_bits = spec["information_bits"]
    parity_bits = variables - information_bits
    parity_masks = []
    if information_bits % 8 == 0 and parity_bits == len(rows):
        left = []
        right = []
        for row_index, row in enumerate(rows):
            left_mask = sum(1 << (information_bits - 1 - column)
                            for column in row if column < information_bits)
            right_mask = sum(1 << (column - information_bits)
                             for column in row if column >= information_bits)
            left.append(left_mask)
            right.append(right_mask | (1 << (parity_bits + row_index)))
        for column in range(parity_bits):
            pivot = next(index for index in range(column, parity_bits)
                         if (right[index] & (1 << column)) != 0)
            right[column], right[pivot] = right[pivot], right[column]
            left[column], left[pivot] = left[pivot], left[column]
            for row_index in range(parity_bits):
                if row_index != column and (right[row_index] & (1 << column)) != 0:
                    right[row_index] ^= right[column]
                    left[row_index] ^= left[column]
        parity_masks = left
    mask_bytes = []
    for value in parity_masks:
        mask_bytes.extend(value.to_bytes(information_bits // 8, "big"))
    masks = ("static const uint8_t " + name + "_parity_masks[] = {\n    " +
             ",\n    ".join(
                 ", ".join(f"0x{byte:02x}U" for byte in
                           mask_bytes[offset:offset + information_bits // 8])
                 for offset in range(0, len(mask_bytes), information_bits // 8)
             ) + "\n};\n") if parity_masks else ""
    mask_pointer = f"{name}_parity_masks" if parity_masks else "NULL"
    return f"""/* Generated by tools/generate_ldpc_table.py; do not edit. */
#ifndef {guard}
#define {guard}

#include \"../ldpc.h\"
#include <stddef.h>
#include <stdint.h>

static const uint16_t {name}_check_offsets[] = {{ {values(offsets)} }};
static const uint16_t {name}_edge_variables[] = {{ {values(edges)} }};
{masks}
static const rtnc_ldpc_code_t {name} = {{
    .variable_count = {variables}U,
    .information_count = {information_bits}U,
    .check_count = {len(rows)}U,
    .edge_count = {len(edges)}U,
    .check_offsets = {name}_check_offsets,
    .edge_variables = {name}_edge_variables,
    .parity_masks = {mask_pointer},
}};

#endif
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render(args.input)
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != generated:
            print(f"generated table is stale: {args.output}", file=sys.stderr)
            return 1
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
